### ISSUE TITLE
Related Resources

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/kubernetes-glue-operator#11]
Capability set resources which are not managed for a Workflow but serves as an input for it.

Should be a related resource name or selector always mandatory? 
That would be nice in first version at least. 

If namespace not set, it is defaulted to namespace of the workflow.

Sample:

```yaml

apiVersion: io.csviri.operator.workflow/v1beta1
kind: Workflow
metadata:
  name: wf-to-change
spec:
  resources:
    - name: configMap1
      resource:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: configmap1
        data:
          key: "{{secret1.data.value}}"
  relatedResources:
    - name: secret1
      resource:
        apiVersion: v1
        kind: Secret
        name: my-secret
        namespace: optional-namespace        
```
